### ISSUE TITLE
Run SEV hardware tests as part of CI

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#105]
We'd like to implement SEV hardware testing as part of our CI pipeline. That is: whenever a new PR is submitted, compile, run, and test the new code on real SEV chips to see if it works in a production environment.

CI providers certainly can't accomplish this alone; we'll have to provide our own hardware. But assuming we have the hardware available to run the tests, we still need to research and develop a way for those tests to happen as seamlessly as possible alongside our standard test pipeline.

With our recent migration to Github Actions, we think having self-hosted runners for SEV code is the best way to go. I (@mbestavros) have access to an SEV box, and will be looking to hook it up with our Actions CI setup.

This issue can be considered complete when the following tasks are done:

- [x] Set up SEV box
  - [x] Install Fedora
  - [x] Install project dependencies
  - [x] Enable the KVM SEV kernel command line parameters in GRUB (mem_encrypt=on kvm_amd.sev=1)
- [x] Make SEV box a Github Actions self-hosted runner
- [x] Compile and test the Enarx project on the SEV box
- [x] Run hardware tests
  - [x] Compile and test the Enarx project on the SEV box via CI with destructive tests enabled
    - [x] Conditionally enable the SEV crate's destructive tests based on a config option of sorts 
- [ ] Document the setup process for setting up self-hosted SEV CI
- [ ] Containerize/automate runner setup (#320)
- [ ] Set up production CI on the test box
- [ ] (Longer term) Set up production CI on test hardware it/when it becomes available

**Comment by mbestavros** [comment]
I'll be taking this on as my next area of focus. Our migration to Github Actions for CI makes that likely the best solution, so I'm editing the main issue with some checks and converting this to a meta issue.

**Comment by mbestavros** [comment]
Pending a more robust writeup, here are the Github resources I used to set up the one we're using:

- [About self-hosted runners](https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners)
- [Adding self-hosted runners](https://help.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners)
- [Using self-hosted runners](https://help.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow)

**Comment by connorkuehl** [comment]
Closed by #765
