### ISSUE TITLE
Add attestation-types crate

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#107]
Types to add include:
- [ ] Quote (depends on #248 )
- [x] Report (depends on #236 )
- [x] TargetInfo ( depends on #170 )

**Comment by lkatalin** [comment]
WIP here: https://github.com/lkatalin/enarx/tree/attestation-types
