### ISSUE TITLE
MVP Attestation

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1183]
# Acceptance Criteria:
- [x] `getatt()` for SEV-SNP is fully functional
- [x] `getatt()` for SGX is fully functional
- [x]  A test which validates the signature on the attestation message for `getatt()` on SEV-SNP
- [x]  A test which validates the signature on the attestation message for `getatt()` on SGX

**Comment by platten** [comment]
@npmccallum Pending acceptance of work and closeout.

**Comment by jarkkojs** [comment]
@npmccallum, @haraldh, @platten: Can we close this or not?

**Comment by haraldh** [comment]
Closing.. please re-open, if you object.
