### ISSUE TITLE
[Feature]: Publish scripts & documentation for local virtualized developer environments (KVM-only)

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Provide an easy path to get started using user experience, around using `enarx` to develop new software and to develop and test functionality not requiring the use of Intel SGX or AMD SEV instructions.

### Acceptance Criteria

- [ ] Create new repository for storing virtual developer environments
  - There should be 2 environments:
    - Unstable environment optimized for core `enarx` developers
    - Stable environment for creating and running user provided content using `enarx`
      - _NOTE: It might be beneficial to add examples in this environment_
- [ ] Test current Vagrant scripts w/ VirtualBox
  - [Vagrantfile to set up Fedora VM using latest code from GitHub & Rust Nightly](https://gist.github.com/platten/0a28d8f4b5fdc5ed45cdddc53828a3b2)
  - [Vagrantfile to set up Fedora VM using stable code from crates.io & pinned Rust nightly release](https://gist.github.com/platten/2821b7f580ed0589199620f8549d18ab2)
- [ ] Optionally add and test `libvirt` provider
- [ ] Provide documentation & instructions in repo
- [ ] Provide documentation on [enarx.dev](https://enarx.dev) website
