### ISSUE TITLE
[Feature]: Release Enarx 0.2 

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Release 0.2 version of Enarx

### Acceptance Criteria
- [x] Release xsave & sallyport before
- [x] Release notes/change log created/updated
- [x] Build passing & documented
- [x] Semver bumped
- [x] GitHub tag/release created
- [x] Pushed to crates.io
- [x] enarx.dev documentation updated/tested
- [x] Posted update on social media
