### ISSUE TITLE
[Feature]: Release v0.2.1

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Release 0.2.1 version of Enarx

### Acceptance Criteria

- [x] Release notes/change log created/updated
- [x]  Build passing & documented
- [x]  Semver bumped
- [x]  GitHub tag/release created
- [x]  Pushed to crates.io
- [x]  enarx.dev documentation updated/tested
- [x]  Posted update on social media

**Comment by platten** [comment]
@nickvidal Any chance you could please post an update on Twitter that the v0.2.1 patch release is out?
