### ISSUE TITLE
[Infrastructure]: Enable Conventional Commit Message Checker

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1421]
### Task List:
- [ ] [enarx/.github](https://github.com/enarx/.github/pull/15)
- [ ] [enarx/enarx](https://github.com/enarx/enarx/pull/1423)
- [ ] [enarx/enarx.github.io](https://github.com/enarx/enarx.github.io/pull/84)
- [ ] [enarx/sallyport](https://github.com/enarx/sallyport/pull/93)
- [ ] [enax/xsave](https://github.com/enarx/xsave/pull/11)
- [ ] [enarx/client](https://github.com/enarx/client/pull/71)
- [ ] [enarx/sevctl](https://github.com/enarx/sevctl/pull/105)
- [ ] [enarx/ciborium](https://github.com/enarx/ciborium/pull/41)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Description

Enable https://github.com/KevinDeJong-TomTom/commisery-action for all enarx org repositories.
