### ISSUE TITLE
shim_kvm on arm64 investigation

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1612]
# Scope
- map X86_64 syscalls over to ARM
  - [ ] `sallyport`: syscall numbers conditionalized
  - [ ] Compile `sallyport` on arm64
- `shim_kvm`
  - [ ] Page tables
  - [ ] initialization code
  - [ ] syscall mechanism / exception handler
- wasmtime dependency tree
  - [ ] Test arm64 backend for cranelift
  - [ ] Bugfixing
- [ ] Cross-compilation for binary dependencies

**Comment by platten** [comment]
- map X86_64 syscalls over to ARM
  - `sallyport`: syscall numbers conditionalized
  - Compile `sallyport` on arm64
- `shim_kvm`
  - Page tables
  - initialization code
  - syscall mechanism / exception handler
- wasmtime dependency tree
  - Test arm64 backend for cranelift
  - Bugfixing
- Crosscompilation for binary dependencies

**Comment by jarkkojs** [comment]
Would be probably appropriate to mention that Realms is in ARMv9 microarchitecture.

**Comment by jarkkojs** [comment]
And the spec is located here: https://developer.arm.com/documentation/ddi0615/latest/. I've skimmed through it briefly some time ago.
