### ISSUE TITLE
[Feature]: Release 0.4 version of Enarx

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Release 0.4 version of Enarx

### Acceptance Criteria

- [ ] Toolchain & dependencies updated
- [ ] Release prerequisite crates
- [ ] Release notes change log created/updated
- [ ] Build passing & documented
- [ ] Semver bumped
- [ ] GitHub tag/release created
- [ ] Pushed to crates.io
- [ ] enarx.dev documentation updated/tested
- [ ] Posted update on social media
- [ ] #1647
