### ISSUE TITLE
[Feature]: Release 0.5 version of Enarx

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Release 0.5 version of Enarx

### Acceptance Criteria

- [x] Updated release notes
- [x] Any pre-release PRs merged
- [x] Maintenance window scheduled
- [x] Pre-release crates tested
- [x] Creates published
- [x] GitHub release drafted
- [x] GitHub release published
- [x] Documentation published
- [x] Announcement made
