### ISSUE TITLE
Enarx v0.5.2 Release

### ISSUE THREAD

**Issue by platten** [enarx/enarx#1942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Release 0.6.0 version of Enarx

### Acceptance Criteria
- [x] Identify castle theme for release: https://en.wikipedia.org/wiki/Fushimi_Castle
- [ ] Versioned documentation updated #1895
- [ ] Prepared release notes including 
- [ ] Any pre-release PRs merged
- [ ] Maintenance window scheduled
- [ ] Pre-release crates tested
- [ ] Crates published
- [ ] GitHub release drafted
- [ ] Artifacts added to release
- [ ] GitHub release published
- [ ] Homebrew Formula updated.
- [ ] Homebrew Formula tested.
- [ ] Winget package updated.
- [ ] Winget package install tested.
- [ ] References added to new versioned documentation #1895
- [ ] Documentation compiled
- [ ] Manual testing of quickstart documentation completed
- [ ] Documentation published
- [ ] Announcement made
