### ISSUE TITLE
Decompose monolithic tasks

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx#233]
Break these down into smaller, more finer grained tasks. This will make it easier to express what is actionable and better describe the way to make progress on these tasks. In some cases, it may even allow contributors to make progress in parallel on the subtasks of one much larger meta task.

In the spirit of #231 (feel free to edit this to break items down). It is likely that some of these issues will be adapted to the meta-issue format:

Documentation

Infrastructure

SEV
- [ ] Merge KVM demo into enarx/enarx (#72)
  - [ ] ???
- [ ] Run the WASM runtime inside a VM (#78)
  - [ ] ???
- [ ] Measure and attest the VM contents (#79)
  - [ ] ???
- [ ] Demonstrate attesting Enarx on SEV and delivering a WASM payload (#80)
  - [ ] ???

SGX

WASM

**Comment by connorkuehl** [comment]
We've added a template for meta/tracker tasks. Those will probably be incorporated heavily when we switch to a more scrum-based workflow.
