### ISSUE TITLE
[Feature]: Consolidated tracking of the threading work in wasi and wasi-libc

### ISSUE THREAD

**Issue by dpal** [enarx/enarx#2362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since the threading work is done in the external project (Wasmtime), a single tracking ticket is better than having several.

Consolidating and closing:
- [[Feature]: implement threading for WASI #2292](https://github.com/enarx/enarx/issues/2292) 
- [[Feature]: implement threading in wasi-libc #2293](https://github.com/enarx/enarx/issues/2293)
- [[Feature]: implement threading for wasmtime #2294](https://github.com/enarx/enarx/issues/2294)

### Acceptance Criteria

Most of the pthread_* functions are implemented and working.

**The main tracking ticket** https://github.com/WebAssembly/wasi-threads/issues/10

Wasmtime:
- [ ] https://github.com/bytecodealliance/wasmtime/pull/5255
- [ ] https://github.com/bytecodealliance/wasmtime/issues/5235 figure out how to lock the WASI contexts which should now be measurable with the benchmarks I made but still has the async problems to resolve
- [ ] start figuring out the refactoring to properly share Arc-wrapped WASI contexts between instances (read: threads).

Wasi-libc
- [ ] https://github.com/WebAssembly/wasi-libc/pull/342 PR for stack and TLS
- [ ] get some test infrastructure up and running a subset of the [libc-test thread tests](http://nsz.repo.hu/git/?p=libc-test;a=blob;f=src/functional/pthread_mutex.c;h=1c048aefeec6b9bde7f2f15b3b49e5e304dfad6a;hb=HEAD)

### Suggestions for a technical implementation

Working prototype: 
https://github.com/haraldh/wasmtime/tree/wasi-threads-working
https://github.com/haraldh/wasi-libc/tree/threads-tls

**Comment by haraldh** [comment]
WIP: https://github.com/bytecodealliance/wasmtime/pull/5326
