### ISSUE TITLE
Migrate Enarx's test suite from Travis to Github Actions

### ISSUE THREAD

**Issue by mbestavros** [enarx/enarx#246]
Following positive results from #213 and enabling GHA with #229, we'd like to move our entire CI test suite over to GHA. This will allow some nice integration with Github's PR UI and sets up some good longer-term CI opportunities.

This can be considered complete when the following tasks have been completed:
- [x] All Travis tests have been moved to Github Actions
  - [x] `cargo build`
  - [x] `cargo test`
  - [x] `cargo audit`
  - [x] `cargo clippy`
  - [x] edition test
  - [x] license test
  - [x] newline test
  - [x] SPDX ID test
  - [x] `cargo.toml` license field test
- [ ] Travis has been disabled
