### ISSUE TITLE
Break down the sev crate into independent crates

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx#280]
Right now the `sev` code lives in the crate called `sev`. It should be broken down into orthogonal crates much like `sgx` is (i.e., `sgx-iocuddle`, `sgx-types`...)

**To do**

- [ ] `sev-types` (#281)
- [ ] `sev-crypto`(#113)
- [ ] `iocuddle-sev` (#202)
- [x] `sev-show` (#216)
- [ ] SEV-functionality in `ketuvim` -> `sev` (#180)
- [ ] `enarx-keep-sev` (from Harald's demo, this is "vmrun")
- [ ] `enarx-keep-sev-shim` (from Harald's demo, this is "kernel")
- [ ] Polish up `sevctl` (https://github.com/enarx/sevctl)

... the list above may grow.

**Comment by connorkuehl** [comment]
This issue has been superseded by the one referenced above.
