### ISSUE TITLE
Intel SGX Static Binary Demo

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#285]
**Description**

We want to deliver a demo of a Hello World static binary running in an SGX Enclave. This does not include attestation, which will be a separate demo. We will consider this issue complete when the demo is fully reproducible and documented. This is not a sequential list. Some of these issues can, and should, be parallelizable (:trident:). High priority issues are marked with :exclamation:.

**To do**

- [ ] Documentation
    - [ ] :trident: Document the architecture and state transitions of the core SGX code
    - [ ] :trident: Document how to run the demo (including hardware requirements)
    - [x] :trident: :exclamation: Inventory the syscalls required for:
        - core musl libc (i.e. `int main() { return 0; }`)
        - C Hello World on musl libc
        - Rust Hello World on musl libc
- [x] :trident: :exclamation: Make an official Enarx Copr Repo
    - [x] :trident: :exclamation: Package SGX out of tree driver
    - [x] :trident: :exclamation: Package SGX debugger
- [x] Run a static-pie binary in an enclave
    - [x] Run some hand-coded assembly in an enclave
        - [x] Define Loader Semantics
        - [x] Write ELF binary loader (`enarx-keep-sgx`)
        - [x] Write initial enclave code (`enarx-keep-sgx-shim`)
    - [x] :exclamation: Handle an enclave exception
        - [x] Build context switching code
        - [x] Create Rust `entry()` function
        - [x] Intentionally generate a fault and handle it in Rust
    - [x] Run an ELF binary that just calls SYS_exit (i.e. `void _start(void) { syscall(...); }`)
    - [x] Run a libc ELF binary that just returns (i.e. `int main() { return 0; }`)
        - [x] Set up crt0 stack
            - [x] :trident: Review and merge `crt0stack` crate
        - [x] Support all additional syscalls needed for libc `_start()` to run
    - [x] Run a C Hello World ELF binary
    - [x] Run a Rust Hello World ELF binary

**Comment by npmccallum** [comment]
@lkatalin FYI

**Comment by mbestavros** [comment]
The SGX portion of demo2020 branch is fully merged into master, so this can be considered complete!

**Comment by npmccallum** [comment]
I was wrong to advise this issue be closed. While the functionality was completely merged as of commit 75d5125c58720be8180e61dd020bb2df5de62932, we still need documentation on how to build and run the demo as well as technical docs on our state transitions.

FYI: @lkatalin @axelsimon

**Comment by npmccallum** [comment]
In spite of missing docs, we're calling this done. Our current code is shifting too fast for documenting this.
