### ISSUE TITLE
 AMD SEV Static Binary Demo

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx#309]
**Description**

We want to deliver a demo of a Hello World static binary running in an SEV-enabled virtual machine. This does not include attestation, which will be a separate demo. We will consider this issue complete when the demo is fully reproducible and documented. This is not a sequential list. Some of these issues can, and should, be parallelizable (:trident:). High priority issues are marked with :exclamation:.

**To do**

- [ ] Documentation
    - [ ] :trident: Document the architecture and state transitions of the core SEV code
    - [x] :trident: Document how to run the demo (including hardware requirements)
    - [x] :trident: :exclamation: Inventory the syscalls required for:
        - [x] core musl libc (i.e. `int main() { return 0; }`)
        - [x] C Hello World on musl libc
        - [x] Rust Hello World on musl libc
- [x] Run a static binary in an SEV-enabled virtual machine
  - [x] Run a toy program in the VM ('app' on Harald's repo, or `code` in Enarx parlance)
    - [x] :trident: Port the hypervisor implementation from Harald's repo (vmrun) (`enarx-keep-sev`) (#313)
      - [x] KVM VM management (create, quit)
      - [x] Load kernel binary into KVM VM
      - [x] Event loop to service requests from the VM (i.e., to proxy syscalls)
    - [x] :trident: Port the microkernel implementation from Harald's repo (kernel) (`enarx-keep-sev-shim`)
      - [x]  :exclamation: **NOTE** - some aspects of parallelizing hypervisor and microkernel porting work may not be 100% parallelizable. For example: the microkernel uses a port to communicate with the hypervisor and the hypervisor does not have an event loop listening on a port to receive the microkernel's requests.
      - ~~Initialize UART (this will be helpful for debug, at least)~~
      - [x] Init GDT
      - ~~Init interrupt controller~~
      - ~~Init timer~~
      - [x] Wire up syscalls
      - [x] Boot strap virtual memory
      - [x] Allocate heap (?)
      - [x] Allocate stack
      - [x] Load ELF binary
        - [x] Determine how the ELF image is communicated to the kernel (the hypervisor will load the kernel and the toy binary, which it will then make available to the kernel)
        - [x] Kernel has a boot parameter where the hypervisor can indicate where in the kernel's address space the toy binary is
      - [x] Context switch (+ transition between rings 0-3)
    - [x] Run an ELF binary that just calls SYS_exit (i.e. `void _start(void) { syscall(...); }`) (#72)
    - [x] Run a libc ELF binary that just returns (i.e. `int main() { return 0; }`) (#77)
    - [x] Support all additional syscalls needed for libc `_start()` to run
    - [x] Run a C Hello World ELF binary
    - [x] Run a Rust Hello World ELF binary
  - [x] Enable SEV in the loader
  - [x] Enable SEV in the shim
    - [x] mark shared pages between loader and shim as unencrypted

**Comment by haraldh** [comment]
I think this can be closed now.

**Comment by haraldh** [comment]
Unless we want to add the SEV encryption step.

**Comment by haraldh** [comment]
Updated the initial comment.
- sync with current state
- additional points

**Comment by connorkuehl** [comment]
Depends on #818

**Comment by connorkuehl** [comment]
Only one task remaining:

> Document the architecture and state transitions of the core SEV code

**Comment by mbestavros** [comment]
We're considering this done!
