### ISSUE TITLE
Implement enarx-keep-sev

### ISSUE THREAD

**Issue by connorkuehl** [enarx/enarx#313]
**Description**

Port [Harald's hypervisor implementation](https://github.com/haraldh/enarx_sev_kvm_demo/tree/master/vmrun) into the Enarx repo. This is called `vmrun` in his repo. It will likely take a slightly different shape than it is in Harald's repo for the sake of integrating it in with the Enarx repo and/or due to some refactoring that Harald mentioned it could benefit from.

**To do**

- [x] `enarx-keep-sev` is a binary crate that we can pass command line arguments to supply file paths to the kernel binary and the "code" binary (the application we will run)
- [x] Create a KVM VM context
- [x] Load the microkernel binary into the virtual machine address space
- [x] Expose a port to the microkernel and add an event loop to service requests from the microkernel (for proxying syscalls/shutting down)
- [x] Inject the program binary that we are running (`code`)
  - [x] Load and copy this binary into the VM's address space
  - [x] Provide a boot/command line argument to the microkernel so that it knows where to find the user binary to run

**Comment by npmccallum** [comment]
@connorkuehl If this is done, please close it.
