### ISSUE TITLE
Implement syscalls required by wasmtime

### ISSUE THREAD

**Issue by ziyi-yan** [enarx/enarx#733]
**Description**

For supporting the WASI implementation of `wasmtime`,  we need to implement all the syscalls required by it on Linux while running [wasi-tests](https://github.com/bytecodealliance/wasmtime/tree/main/crates/test-programs/wasi-tests).

Here is the total 44 syscalls ([bash script](https://gist.github.com/ziyi-yan/03b30d7a67dc4e44bac5783f3e619c44) for collating):

- [ ] access
- [ ] arch_prctl
- [ ] brk
- [ ] clock_gettime
- [ ] clone
- [ ] close
- [ ] execve
- [ ] fadvise64
- [ ] fcntl
- [ ] fstat
- [ ] ftruncate
- [ ] futex
- [ ] getdents64
- [ ] getrandom
- [ ] ioctl
- [ ] linkat
- [ ] lseek
- [ ] lstat
- [ ] mkdir
- [ ] mkdirat
- [ ] mmap
- [ ] mprotect
- [ ] munmap
- [ ] newfstatat
- [ ] openat
- [ ] poll
- [ ] prlimit64
- [ ] read
- [ ] readlink
- [ ] readlinkat
- [ ] readv
- [ ] renameat
- [ ] rt_sigaction
- [ ] rt_sigprocmask
- [ ] sched_getaffinity
- [ ] sched_yield
- [ ] set_robust_list
- [ ] set_tid_address
- [ ] sigaltstack
- [ ] statx
- [ ] symlinkat
- [ ] unlinkat
- [ ] utimensat
- [ ] writev

*This issue is still under construction.*
**To Do**
- [ ] group syscalls into multiple meta-issue as logical sets

**Comment by npmccallum** [comment]
@ziyi-yan I presume that most of the filesystem related syscalls are related to WASI filesystem related functions. Can you find a way to not run those WASI functions since we don't plan to support them for v1.0?

**Comment by kubkon** [comment]
@ziyi-yan I can quickly scribble a mod to `wasmtime` to turn off those if it'd be of help. It would look like this mod that I've done which enforces determinism in `wasmtime`: [kubkon/wasi-compute](https://github.com/kubkon/wasi-compute). Lemme know if that'd be useful to you!

**Comment by npmccallum** [comment]
@kubkon That sounds like exactly like what we need: WASI without filesystem functions.

**Comment by kubkon** [comment]
@ziyi-yan as part of the prep for virtual dispatcher work in `wasmtime` I did a while back, I compiled a list of WASI syscalls based on the handle type and what they can support. To give an example, we differentiate a couple of types already with the intention of having the system fully modular in the future, and so, we have a file handle, dir handle, virtual file handle, etc. To provide some context, virtual dispatcher will be an intermediate layer in `wasmtime`, between WASI syscalls implementation and the guest module, which will give the runtime certain automatic decision capabilities in terms of which syscall to route for the given WASI syscall based on its type. We will finally be able to decide whether the handle is a file, a dir, a stream or a socket and route it to an appropriate WASI module.

Anyhow, since `enarx` will not want to support any file/path ops, here's the list of current WASI syscalls that are non-file/non-path oriented.

#### File descriptor oriented:
* `fd_fdstat_get`
* `fd_fdstat_set_flags`
* `fd_filestat_get`
* `fd_filestat_set_times`
* `fd_read`
* `fd_write`
* `fd_close`
* `fd_renumber`

#### Args and env:
* `args_get`
* `args_sizes_get`
* `environ_get`
* `environ_sizes_get`

#### Clocks:
* `clock_res_get`
* `clock_time_get`

#### Polling:

OK, I have to admit, I'm not sure about this one. @npmccallum is it planned for poll to be supported? Or put it another way, is it viable at all from within a keep?

* `poll_oneoff`

#### Preopens (currently optional):

*NB Currently preopens are effectively only directories; however, in the future, the idea is that there will be a plethora of different handles the user will be able to preopen for the guest module to make use of such as a range of ports, etc.*

* `fd_prestat_get`
* `fd_prestat_dir_name`

#### Entropy
* `random_get`

#### Sockets

*NB They are currently unimplemented in `wasmtime`.*

* `sock_recv`
* `sock_send`
* `sock_shutdown`

#### Others:
* `proc_exit`
* `sched_yield`

**Comment by ziyi-yan** [comment]
@kubkon Thanks for your work on categorized those syscalls!

It seems that we cannot isolate file descriptor oriented functions from some file system functions like `path_open`  in [`wasi-tests`](https://github.com/bytecodealliance/wasmtime/tree/main/crates/test-programs/wasi-tests). `fd_read`/`fd_write`/`fd_close`/`fd_renumber` need `path_open` to create a `Fd` to operate on.

There is no test program in wasi-tests involve **Args and env** functions, `clock_res_get` and `proc_exit`. But I think we can write some test programs calling those functions.

`sock_*` functions are not implemented in wasmtime yet. 

@kubkon I checked out your talks about determinism in WASI, is that possible to run test programs with only file descriptor oriented functions with `wasi-compute`? I will try it out on my laptop today and try to dig into it about how it works. It would be really appreciate if you can give me any pointers about it. Thanks!

**Comment by kubkon** [comment]
@ziyi-yan In short no, but we can chop up those tests into only a subset of what we actually need. If you can wait a day or two, I'll be happy to look into it, or help you out with this if you want to take it on :-) The trick here will be tweaking `keep-runtime` to preopen handles rather than paths. Now that I think of it, perhaps we should add an issue to that effect to track this. What do you think @npmccallum @ueno?

BTW, if we do write a set of tests for the noncovered syscalls, that'd be amazing and we should definitely push it upstream.

**Comment by ziyi-yan** [comment]
Thanks, @kubkon! I'd like to take it on if it's not hard to explain or demonstrate how to get it done.

**Comment by ueno** [comment]
@kubkon that reminds me of my (stupid) [idea](https://github.com/enarx/rfcs/blob/c261d5f7a676e7cfcc7dda81112ae389b1a9ab81/features/workload-package-format/README.md) of making bundled application data visible as virtual fs ;-)

**Comment by npmccallum** [comment]
@ueno That's not a stupid idea. I've had exactly the same idea.

With WASI there is no singe "/" because you only get `openat()`. So we can have a `bundled` handle that points to a vfs for bundled data.

**Comment by kubkon** [comment]
@ueno I think this is great! If we had this bundling done, using custom sections, we'd need to look into tweaking `wasmtime` into understanding the custom sections, and then we could use my [wasi-compute](https://github.com/kubkon/wasi-compute) hack to preopen the virtual handles instead. Do you know if `wasmtime` supports custom section, and more importantly, I wonder if Rust/`rustwasm` does. I'll need to investigate closer and also, we need to sync up over a call @ueno!

**Comment by platten** [comment]
We are currently running `wasmtime` and this is a non-issue.
