### ISSUE TITLE
Measure and attest SGX contents

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#84]
Depends on #82.

**Comment by lkatalin** [comment]
Summer 2020 SGX attestation-related tasks:

These are tasks that can be done without the communication channels between enclave and client established yet.

### Enclave side (generating the attestation Report):
- [ ] Detect whether payload is running in SGX or SEV #671 
- [ ] Receive and handle an attestation request TODO: in shim layer or code layer?
- [ ] Generate a Report for the current enclave using EREPORT
- [ ] Generate a Diffie-Hellman keys **
- [ ] Embed DH pub key in the Report **

### Enarx Client Agent side (verifying a Quote):
- [ ] Create an attestation request (to be later sent to enclave side)
- [ ] Retrieve a PCK cert chain from Intel’s service
- [ ] Check validity of the PCK cert chain
- [ ] Verify a dummy Quote:
  - [ ] Parse the Quote: get measurement, PCK leaf cert, signatures, etc.
  - [ ] Verify PCK is correct via PCK cert chain
  - [ ] Verify AK is correct via PCK
  - [ ] Verify AK signature on measurement is correct
  - [ ] Verify measurement is expected
- [ ] Generate Diffie-Hellman keys **

** = Requires further discussion / RFC underway

**Comment by platten** [comment]
Closing in lieu of #1212
