### ISSUE TITLE
[meta] Add testing for syscalls

### ISSUE THREAD

**Issue by lkatalin** [enarx/enarx#961]
### Integration test overview
An integration test for a syscall runs a minimal binary in the Keep and checks the results. Writing an integration test involves creating the [binary](https://github.com/enarx/enarx-keepldr/tree/master/tests/bin) itself (at least one per each syscall to test) and updating the [test harness](https://github.com/enarx/enarx-keepldr/blob/master/tests/integration_tests.rs) to run this binary in the Keep during `cargo test`. Some syscalls have more than one binary for different variations of parameters, ex. `exit` or `write` each have several varieties to test different exit codes or to test writing to different file descriptors.

Each syscall test is implemented in [C inline assembly](https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html#Extended-Asm) in our [`libc.h`](https://github.com/enarx/enarx-keepldr/blob/master/tests/bin/libc.h) file. The corresponding C binary file for each syscall then refers to this implementation by [including](https://github.com/enarx/enarx-keepldr/blob/master/tests/bin/write_stdout.c#L1) our `libc.h` and [calling](https://github.com/enarx/enarx-keepldr/blob/master/tests/bin/write_stdout.c#L6) the correct function. The test harness is written in Rust and actually [runs](https://github.com/enarx/enarx-keepldr/blob/master/tests/integration_tests.rs#L191) the binary in a Keep. See the [`run_test()`](https://github.com/enarx/enarx-keepldr/blob/master/tests/integration_tests.rs#L51) function for more on how to pass inputs and receive outputs from the test.

**Example: syscall test for write()**
1. Create a C inline assembly [implementation](https://github.com/enarx/enarx-keepldr/blob/master/tests/bin/libc.h#L66) for write in `libc.h`
2. Create a [C binary](https://github.com/enarx/enarx-keepldr/blob/master/tests/bin/write_stdout.c) that uses your implementation
3. Add a Rust [test](https://github.com/enarx/enarx-keepldr/blob/master/tests/integration_tests.rs#L191) to run this binary in a Keep and check that the outputs and return status code are expected

### Syscalls to test
Choose a syscall that is not checked off to test. Edit this list to indicate you are working on it so that someone else does not duplicate the work, ex. by writing "current WIP" next to the syscall on the list.
- [X] read(),
- [X] readv(),
- [X] write(),
- [X] writev(),
- [X] exit(),
- [x] getuid(),
- [x] arch_prctl(),
- [x] exit_group(),
- [ ] set_tid_address(),
- [x] brk(),
- [x] uname(),
- [ ] mprotect(),
- [x] mmap(),
- [ ] munmap(),
- [ ] rt_sigaction(),
- [ ] rt_sigprocmask(),
- [ ] sigaltstack(),
- [x] getrandom(),
- [X] clock_gettime(),
- [ ] madvise(),
- [x] close()
- [ ] pipe
- [ ] fcntl with F_GETFD, F_SETFD, F_GETFL, F_SETFL
- [ ] ioctl with FIONBIO
- [ ] getsockname
- [ ] sendto
- [ ] setsockopt
- [ ] epoll_create1
- [ ] epoll_ctl
- [ ] epoll_wait
- [x] getpid

### Extra info about syscall implementations
Syscalls are implemented internally [here](https://github.com/enarx/enarx-keepldr/blob/master/internal/syscall/src/lib.rs) (these are handled in the Keep or if necessary are proxied out to the host). Each architecture can also override these definitions in its own handler: see the handlers for [SGX](https://github.com/enarx/enarx-keepldr/blob/master/internal/shim-sgx/src/handler.rs#L123) and [SEV](https://github.com/enarx/enarx-keepldr/blob/master/internal/shim-sev/src/syscall.rs#L164). In SGX, syscalls are passed to the handler from the [event](https://github.com/enarx/enarx-keepldr/blob/master/internal/shim-sgx/src/event.rs#L33) file. In SEV, syscalls are passed to the handler from [here](https://github.com/enarx/enarx-keepldr/blob/master/internal/shim-sev/src/syscall.rs#L129).

[Here](https://github.com/enarx/enarx/issues/733) is a master list of syscalls required by wasmtime, for reference. Which of these syscalls we will implement from this list is TBD.

**Comment by platten** [comment]
Since we are focusing on testing user experience vs. syscalls, marking this as closed.
